export const GET_COUNTRIES_LIST_SUCCESS = 'GET_COUNTRIES_LIST_SUCCESS';
export const GET_COUNTRIES_LIST_ERROR = 'GET_COUNTRIES_LIST_ERROR';

export const GET_COUNTRIES_DATA_SUCCESS = 'GET_COUNTRIES_DATA_SUCCESS';
export const GET_COUNTRIES_DATA_ERROR = 'GET_COUNTRIES_DATA_ERROR';

export const GET_ONE_COUNTRY_DATA_SUCCESS = 'GET_ONE_COUNTRY_DATA_SUCCESS';
export const GET_ONE_COUNTRY_DATA_ERROR = 'GET_ONE_COUNTRY_DATA_SUCCESS';
