export const GET_COUNTRIES_LIST_SUCCESS = 'GET_COUNTRIES_LIST_SUCCESS';
export const GET_ONE_COUNTRY_DATA_SUCCESS = 'GET_ONE_COUNTRY_DATA_SUCCESS';
export const SHOW_TOP_RECOVERED = 'SHOW_TOP_RECOVERED';
